# Fly.io configuration for Open CORS Proxy
app = "open-cors-proxy"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  builder = "heroku/buildpacks:20"

[env]
  NODE_ENV = "production"
  PORT = "8080"
  RATE_LIMIT_MAX = "1000"
  RATE_LIMIT_WINDOW = "900000"
  REQUEST_TIMEOUT = "30000"
  MAX_BODY_SIZE = "10mb"
  ALLOWED_ORIGINS = "*"
  DEBUG_HEADERS = "false"
  DEBUG_ERRORS = "false"
  INCLUDE_CONFIG = "false"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [http_service.checks]
    [http_service.checks.health]
      grace_period = "10s"
      interval = "30s"
      method = "GET"
      timeout = "5s"
      path = "/health"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "30s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = false
    headers = {}

[deploy]
  release_command = "echo 'Open CORS Proxy deployment starting...'"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256