services:
  - type: web
    name: open-cors-proxy
    env: node
    plan: starter
    region: oregon
    buildCommand: npm install --production
    startCommand: npm start
    healthCheckPath: /health
    numInstances: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PROXY_API_KEY
        generateValue: true
      - key: ADMIN_API_KEY
        generateValue: true
      - key: RATE_LIMIT_MAX
        value: "1000"
      - key: RATE_LIMIT_WINDOW
        value: "900000"
      - key: REQUEST_TIMEOUT
        value: "30000"
      - key: MAX_BODY_SIZE
        value: "10mb"
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: BLOCKED_DOMAINS
        value: ""
      - key: DEBUG_HEADERS
        value: "false"
      - key: DEBUG_ERRORS
        value: "false"
      - key: INCLUDE_CONFIG
        value: "false"
    routes:
      - type: redirect
        source: /
        destination: /health
    autoDeploy: true
    branch: main